# Exercises dataframes


In [36]:
#Import the necessary packages
import pandas as pd

## 1. Soccer

Create a Pandas dataframe containing the `soccer_data`. Every list contains following data: 
- Player name
- Position
- Club
- Goals scored
- Age

Give the columns of the DataFrame appropriate names.

In [37]:
soccer_data = [
    ['Lionel Messi', 'Forward', 'Inter Miami', 30, 12],
    ['Cristiano Ronaldo', 'Forward', 'Al Nassr', 25, 10],
    ['Neymar Jr', 'Forward', 'Al Hilal', 20, 18],
    ['Kylian Mbappe', 'Forward', 'PSG', 35, 15],
    ['Kevin De Bruyne', 'Midfielder', 'Manchester City', 15, 20],
    ['Mohamed Salah', 'Forward', 'Liverpool', 28, 14],
    ['Robert Lewandowski', 'Forward', 'Barcelona', 33, 9],
    ['Karim Benzema', 'Forward', 'Real Madrid', 27, 11],
    ['Luka Modric', 'Midfielder', 'Real Madrid', 10, 22],
    ['Erling Haaland', 'Forward', 'Manchester City', 40, 8]
]


In [38]:
# Create dataframe
dataframe = pd.DataFrame(soccer_data, columns=['Player name', 'Position', 'Club', 'Goals scored', 'Age'])

dataframe


Player name    Position             Club  Goals scored  Age
0        Lionel Messi     Forward      Inter Miami            30   12
1   Cristiano Ronaldo     Forward         Al Nassr            25   10
2           Neymar Jr     Forward         Al Hilal            20   18
3       Kylian Mbappe     Forward              PSG            35   15
4     Kevin De Bruyne  Midfielder  Manchester City            15   20
5       Mohamed Salah     Forward        Liverpool            28   14
6  Robert Lewandowski     Forward        Barcelona            33    9
7       Karim Benzema     Forward      Real Madrid            27   11
8         Luka Modric  Midfielder      Real Madrid            10   22
9      Erling Haaland     Forward  Manchester City            40    8

**Renaming column** \
It seems, we made a mistake. Lionel Messi isn't 12 years old and Kevin De Bruyne isn't 20 either. \
Change the last column's name to "Assists" instead of "Age". Ensure the dataframe itself is affected.

In [39]:
# Renaming column
dataframe.rename(columns={'Age': 'Assists'})

Player name    Position             Club  Goals scored  Assists
0        Lionel Messi     Forward      Inter Miami            30       12
1   Cristiano Ronaldo     Forward         Al Nassr            25       10
2           Neymar Jr     Forward         Al Hilal            20       18
3       Kylian Mbappe     Forward              PSG            35       15
4     Kevin De Bruyne  Midfielder  Manchester City            15       20
5       Mohamed Salah     Forward        Liverpool            28       14
6  Robert Lewandowski     Forward        Barcelona            33        9
7       Karim Benzema     Forward      Real Madrid            27       11
8         Luka Modric  Midfielder      Real Madrid            10       22
9      Erling Haaland     Forward  Manchester City            40        8

**Change the index labels** to player1, player2 etc.

In [40]:
# Index labels
dataframe.index = [f'player{i+1}' for i in range(len(dataframe))]

dataframe

Player name    Position             Club  Goals scored  Age
player1         Lionel Messi     Forward      Inter Miami            30   12
player2    Cristiano Ronaldo     Forward         Al Nassr            25   10
player3            Neymar Jr     Forward         Al Hilal            20   18
player4        Kylian Mbappe     Forward              PSG            35   15
player5      Kevin De Bruyne  Midfielder  Manchester City            15   20
player6        Mohamed Salah     Forward        Liverpool            28   14
player7   Robert Lewandowski     Forward        Barcelona            33    9
player8        Karim Benzema     Forward      Real Madrid            27   11
player9          Luka Modric  Midfielder      Real Madrid            10   22
player10      Erling Haaland     Forward  Manchester City            40    8

## 2. More soccer

This time, the soccer data is stored in a dictionary containing lists. The values of the dictionary, are lists containing the data of a column, the keys are the column names. Create a dataframe using the `soccer_data` below.

In [43]:
soccer_data = {
    'Player Name': [
        'Lionel Messi', 'Cristiano Ronaldo', 'Neymar Jr', 'Kylian Mbappe', 'Kevin De Bruyne', 
        'Mohamed Salah', 'Robert Lewandowski', 'Karim Benzema', 'Luka Modric', 'Erling Haaland'
    ],
    'Player Number': [10, 7, 11, 9, 17, 12, 8, 19, 3, 2],
    'Position': [
        'Forward', 'Forward', 'Forward', 'Forward', 'Midfielder', 
        'Forward', 'Forward', 'Forward', 'Midfielder', 'Forward'
    ],
    'Club': [
        'Inter Miami', 'Al Nassr', 'Al Hilal', 'PSG', 'Manchester City', 
        'Liverpool', 'Barcelona', 'Real Madrid', 'Real Madrid', 'Manchester City'
    ],
    'Goals Scored (Season)': [30, 25, 20, 35, 15, 28, 33, 27, 10, 40],
    'Assists (Season)': [12, 10, 18, 15, 20, 14, 9, 11, 22, 8]
}


In [52]:
# Create DataFrame
dataframe2 = pd.DataFrame(soccer_data)

dataframe2

Player Name  Player Number    Position             Club  \
0        Lionel Messi             10     Forward      Inter Miami   
1   Cristiano Ronaldo              7     Forward         Al Nassr   
2           Neymar Jr             11     Forward         Al Hilal   
3       Kylian Mbappe              9     Forward              PSG   
4     Kevin De Bruyne             17  Midfielder  Manchester City   
5       Mohamed Salah             12     Forward        Liverpool   
6  Robert Lewandowski              8     Forward        Barcelona   
7       Karim Benzema             19     Forward      Real Madrid   
8         Luka Modric              3  Midfielder      Real Madrid   
9      Erling Haaland              2     Forward  Manchester City   

   Goals Scored (Season)  Assists (Season)  
0                     30                12  
1                     25                10  
2                     20                18  
3                     35                15  
4                     15                20  
5                     28                14  
6                     33                 9  
7                     27                11  
8                     10                22  
9                     40                 8

You see we have an extra column `Player Number` containing the player's shirt numbers. Use this data to set the index labels. Doing so, you see two dark grey rows on top containing names. Remove the index column name.

❓ Is it a good idea to use the players's numbers as index labels? Why (not)?

In [ ]:
# Index labels
dataframe2.set_index('Player Number', inplace=True)

dataframe2


Player Name    Position             Club  \
Player Number                                                    
10                   Lionel Messi     Forward      Inter Miami   
7               Cristiano Ronaldo     Forward         Al Nassr   
11                      Neymar Jr     Forward         Al Hilal   
9                   Kylian Mbappe     Forward              PSG   
17                Kevin De Bruyne  Midfielder  Manchester City   
12                  Mohamed Salah     Forward        Liverpool   
8              Robert Lewandowski     Forward        Barcelona   
19                  Karim Benzema     Forward      Real Madrid   
3                     Luka Modric  Midfielder      Real Madrid   
2                  Erling Haaland     Forward  Manchester City   

               Goals Scored (Season)  Assists (Season)  
Player Number                                           
10                                30                12  
7                                 25                10  
11                                20                18  
9                                 35                15  
17                                15                20  
12                                28                14  
8                                 33                 9  
19                                27                11  
3                                 10                22  
2                                 40                 8

**Indexing** 
- Display the club of Kevin De Bruyne
- Change the club of Kevin De Bruyne to "Red Devils"
- Display the Player Name column
- Display the data of the player with shirt number 7, using both integer and label position


In [55]:
#Indexing

# Display the club of Kevin De Bruyne
dataframe2.loc[dataframe2['Player Name'] == 'Kevin De Bruyne', 'Club']

# Change the club of Kevin De Bruyne
dataframe2.loc[dataframe2['Player Name'] == 'Kevin De Bruyne', 'Club'] = 'Red Devils'

# Display Player Name column
dataframe2['Player Name']

# Display the data of the player with shirt number 7 (two of them)
dataframe2.loc[7]


Player Name              Cristiano Ronaldo
Position                           Forward
Club                              Al Nassr
Goals Scored (Season)                   25
Assists (Season)                        10
Name: 7, dtype: object

**Slicing** 
- Display the players with shirt number 10, 7 and 11 using both integer and label position
- Display the players with at least 10 assists
- Display all midfield players
- Display the Player Name, Position and Club of Karim, Luka and Erling

In [59]:
#Slicing

# Players with shirt numbers 10, 7, and 11 (label-based)
dataframe2.loc[[10, 7, 11]]

# Players with shirt numbers 10, 7, and 11 (integer-based)
dataframe2.iloc[[0, 1, 2]]

# Players with at least 10 assists
dataframe2[dataframe2['Assists (Season)'] >= 10]

# All midfield players
dataframe2[dataframe2['Position'] == 'Midfielder']

# Players with more than 25 goals
dataframe2[dataframe2['Goals Scored (Season)'] > 25]


Player Name Position             Club  \
Player Number                                                 
10                   Lionel Messi  Forward      Inter Miami   
9                   Kylian Mbappe  Forward              PSG   
12                  Mohamed Salah  Forward        Liverpool   
8              Robert Lewandowski  Forward        Barcelona   
19                  Karim Benzema  Forward      Real Madrid   
2                  Erling Haaland  Forward  Manchester City   

               Goals Scored (Season)  Assists (Season)  
Player Number                                           
10                                30                12  
9                                 35                15  
12                                28                14  
8                                 33                 9  
19                                27                11  
2                                 40                 8


## 3. Employees
In this lab exercise, you will explore a dataset containing information about employees in a company using Pandas. You will perform various data manipulation and analysis tasks to gain insights into the employee data.

**Dataset:**
You are provided with a dictionary `employee_data` containing employee information:

In [60]:
employee_data = {
    'EmployeeID': [
        101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
        111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
        121, 122, 123, 124, 125, 126, 127, 128, 129, 130
    ],
    'Name': [
        'Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack',
        'Katherine', 'Leo', 'Mia', 'Nathan', 'Olivia', 'Paul', 'Quinn', 'Rachel', 'Samuel', 'Tina',
        'Uma', 'Victor', 'Wendy', 'Xander', 'Yasmine', 'Zack', 'Adam', 'Bella', 'Chris', 'Diana'
    ],
    'Department': [
        'HR', 'IT', 'Finance', 'Marketing', 'Sales', 'IT', 'HR', 'Finance', 'Marketing', 'Sales',
        'IT', 'HR', 'Finance', 'Marketing', 'Sales', 'HR', 'IT', 'Finance', 'Marketing', 'Sales',
        'IT', 'HR', 'Finance', 'Marketing', 'Sales', 'HR', 'IT', 'Finance', 'Marketing', 'Sales'
    ],
    'Salary': [
        60000, 75000, 80000, 70000, 65000, 72000, 68000, 81000, 69000, 66000,
        77000, 64000, 85000, 73000, 67000, 61000, 79000, 82000, 74000, 66000,
        78000, 62000, 83000, 76000, 71000, 63000, 80000, 75000, 87000, 72000
    ]
}


**DataFrame Creation:**
- Create a Pandas DataFrame named 'employees' from the provided dictionary 'employee_data'.
- Use their employee number as row index. Remove the row index column name.

**Data Exploration:**
- Display the first 3 rows of the DataFrame to get an overview of the data. 
- Check the summary statistics for the 'Salary' column. 
- Determine the number of employees in each department.

**Data Analysis:**
- Display the min, max, mean and median of the 'Salary' column.
- Identify the employee(s) with the highest salary and their details.
- Determine the department with the lowest average salary.
- Add a new column 'Salary Increase' to the DataFrame, where each employee's salary is increased by 10%.

In [ ]:
# Your code

employees = pd.DataFrame(employee_data)
employees.set_index('EmployeeID', inplace=True)
employees.index.name = None
employees

Name Department  Salary
101      Alice         HR   60000
102        Bob         IT   75000
103    Charlie    Finance   80000
104      David  Marketing   70000
105       Emma      Sales   65000
106      Frank         IT   72000
107      Grace         HR   68000
108     Hannah    Finance   81000
109        Ian  Marketing   69000
110       Jack      Sales   66000
111  Katherine         IT   77000
112        Leo         HR   64000
113        Mia    Finance   85000
114     Nathan  Marketing   73000
115     Olivia      Sales   67000
116       Paul         HR   61000
117      Quinn         IT   79000
118     Rachel    Finance   82000
119     Samuel  Marketing   74000
120       Tina      Sales   66000
121        Uma         IT   78000
122     Victor         HR   62000
123      Wendy    Finance   83000
124     Xander  Marketing   76000
125    Yasmine      Sales   71000
126       Zack         HR   63000
127       Adam         IT   80000
128      Bella    Finance   75000
129      Chris  Marketing   87000
130      Diana      Sales   72000

## 4. Sales data

In [ ]:
import numpy as np

sales_data = {
    'Product_ID': list(range(101, 151)),
    'Product_Name': [
        'Laptop', 'Smartphone', 'Tablet', 'Headphones', 'Smartwatch', 'Gaming Console', 'Keyboard', 'Mouse', 
        'Monitor', 'Printer', 'Speaker', 'Camera', 'External Hard Drive', 'Router', 'Microphone',
        'Smart TV', 'Projector', 'Power Bank', 'VR Headset', 'Graphics Card', 'Processor', 'RAM', 
        'Motherboard', 'SSD', 'HDD', 'USB Flash Drive', 'Cooling Pad', 'Tripod', 'Streaming Device', 
        'E-Reader', 'Wireless Charger', 'Portable Speaker', 'Game Controller', 'Webcam', 'Smart Light', 
        'Smart Doorbell', 'Fitness Band', 'Drone', 'Bluetooth Adapter', 'Drawing Tablet', 'Coffee Maker', 
        'Air Purifier', 'Robot Vacuum', 'Electric Kettle', 'Blender', 'Toaster', 'Smart Refrigerator', 
        'Washing Machine', 'Oven', 'Microwave'
    ],
    'Category': [
        'Electronics', 'Electronics', 'Electronics', 'Accessories', 'Electronics', 'Gaming', 'Accessories', 
        'Accessories', 'Electronics', 'Office Supplies', 'Audio', 'Photography', 'Storage', 'Networking', 
        'Audio', 'Electronics', 'Office Supplies', 'Accessories', 'Gaming', 'Computer Components', 
        'Computer Components', 'Computer Components', 'Computer Components', 'Storage', 'Storage', 
        'Accessories', 'Accessories', 'Photography', 'Streaming', 'Electronics', 'Accessories', 'Audio', 
        'Gaming', 'Accessories', 'Smart Home', 'Smart Home', 'Wearable', 'Drones', 'Accessories', 
        'Accessories', 'Home Appliances', 'Home Appliances', 'Home Appliances', 'Home Appliances', 
        'Home Appliances', 'Home Appliances', 'Home Appliances', 'Home Appliances', 'Home Appliances'
    ],
    'Price': [
        1200, 800, 400, 100, 300, 500, 50, 40, 250, 150, 200, 700, 120, 90, 60, 1000, 850, 35, 
        600, 400, 300, 150, 200, 180, 130, 20, 45, 100, 120, 250, 75, 220, 55, 90, 200, 180, 
        150, 300, 110, 150, 180, 220, 100, 120, 400, 500, 450, 350, 320
    ],
    'Quantity_Sold': [
        50, 100, 80, 200, 120, 75, 95, np.nan, 60, 110, 130, 40, np.nan, 85, 90, 55, 30, 200, 
        35, np.nan, 65, 45, 100, 70, 85, 150, np.nan, 90, 50, 200, 105, 65, 140, 55, 60, 70, 
        np.nan, 30, 45, 90, 35, 60, 95, np.nan, 110, 75, 55, 80, 100
    ],
    'Brand': [
        'Dell', 'Apple', 'Samsung', 'Sony', 'Fitbit', 'Microsoft', 'Logitech', 'HP', 'LG', 'Canon', 
        'JBL', 'Nikon', 'Seagate', 'TP-Link', 'Blue Yeti', 'Samsung', 'Epson', 'Anker', 'Oculus', 
        'NVIDIA', 'Intel', 'Corsair', 'ASUS', 'Kingston', 'Western Digital', 'SanDisk', 'Cooler Master', 
        'Manfrotto', 'Roku', 'Amazon', 'Belkin', 'Bose', 'Xbox', 'Logitech', 'Philips', 'Ring', 
        'Garmin', 'DJI', 'TP-Link', 'Wacom', 'Keurig', 'Dyson', 'iRobot', 'Breville', 'Ninja', 'Cuisinart', 
        'Samsung', 'LG', 'Bosch', 'Panasonic'
    ],
    'Release_Year': [
        2021, 2020, 2019, 2022, 2021, 2020, 2018, 2017, 2019, 2022, 2021, 2020, 2019, 2021, 2018, 
        2022, 2021, 2020, 2023, 2021, 2019, 2020, 2018, 2022, 2023, 2017, 2018, 2019, 2020, 2021, 
        2018, 2019, 2022, 2020, 2021, 2023, 2022, 2018, 2020, 2019, 2021, 2023, 2020, 2022, 2021, 
        2019, 2018, 2020, 2023
    ],
    'Ratings': [
        4.5, 4.7, 4.3, 4.2, 4.6, 4.8, 4.0, np.nan, 4.1, 4.3, 4.6, 4.7, np.nan, 4.5, 4.0, 
        4.4, 4.1, 3.9, 4.9, np.nan, 4.2, 4.0, 4.3, 4.6, 4.8, 4.1, np.nan, 4.5, 4.2, 4.7, 
        4.0, 4.3, 4.1, 4.6, 4.2, 4.8, 4.9, np.nan, 4.0, 4.1, 4.3, 4.6, 4.2, 4.5, np.nan, 
        4.7, 4.3, 4.2, 4.8
    ]
}


**DataFrame Creation:**
- Create a Pandas DataFrame named 'sales' from the provided dictionary 'sales_data'.
    <details>
    <summary> error? </summary>
    When trying to create a DataFrame, you get an error. The values of the dictionary are not of equal length... Meaning, the last entry/entries is/are incomplete. Omit these entries to create the DataFrame.
    </details>

- Use the Product ID's as index and remove the index heading.
- Set all NaN values in the "Quantity_Sold" column to 0.
- Delete rows containing NaN values except if they only occur in the ratings column. Check the documentation of the known method to delete rows containing NaN's. 
- Show the first 5 rows (without using slicing) and display information about the DataFrame.
- Show the dimensions of the DataFrame

**Indexing and Slicing:**
- Access the last 2 rows and the 'Product_Name' and 'Price' columns using both label-based and positional-based indexing.
- Extract the data for products with product id's 105 to 118 and all columns using integer-based indexing.
    - Don't start counting the rows. It might be useful to reset de indices back to position integers. We still want to keep the Product_ID in our DataFrame, make a new column for this data with an appropriate name.
- **Boolean filtering:** Filter the data to include only products priced below 100.

In [77]:
# Your code

sales = pd.DataFrame(sales_data)

sales.set_index('Product_ID', inplace=True)
# sales.index.name = None

sales['Quantity_Sold'].fillna(0, inplace=True)

sales.dropna(subset=[col for col in sales.columns if col != 'Ratings'], inplace=True)

print(sales.head())
print("\n")
print(sales.info())

print(sales.shape)

print(sales.loc[sales.index[-2:], ['Product_Name', 'Price']])

print(sales.iloc[-2:, [sales.columns.get_loc('Product_Name'), sales.columns.get_loc('Price')]])

sales_reset = sales.reset_index()

subset = sales_reset[(sales_reset['Product_ID'] >= 105) & (sales_reset['Product_ID'] <= 118)]

print(subset)

cheap_products = sales[sales['Price'] < 100]
print(cheap_products)


           Product_Name     Category  Price  Quantity_Sold    Brand  \
Product_ID                                                            
101              Laptop  Electronics   1200           50.0     Dell   
102          Smartphone  Electronics    800          100.0    Apple   
103              Tablet  Electronics    400           80.0  Samsung   
104          Headphones  Accessories    100          200.0     Sony   
105          Smartwatch  Electronics    300          120.0   Fitbit   

            Release_Year  Ratings  
Product_ID                         
101                 2021      4.5  
102                 2020      4.7  
103                 2019      4.3  
104                 2022      4.2  
105                 2021      4.6  


<class 'pandas.core.frame.DataFrame'>
Index: 49 entries, 101 to 149
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Product_Name   49 non-null     object 
 1   Category   

/var/folders/f3/0mb92rs13ln3084yt9jvdws40000gn/T/ipykernel_9272/1731394633.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sales['Quantity_Sold'].fillna(0, inplace=True)


### 4. Sales data part 2

* Read in the additional sales data, stored in the csv file "sales_data.csv" and create a new DataFrame.
* Inspect the file before reading in the data!
* Combine the first sales DataFrame with this new DataFrame in a DataFrame `all_sales`. Ensure both DataFrames are combined correctly. The resulting DataFrame should be of shape 149x8.
* Sort the data from eldest to newest
* Reset the indices to their integer positions, without adding an extra column with the current index label
* Write the resulting DataFrame to a new csv file "all_sales.csv".

In [80]:
# Sales data part 2

# Your code

with open('sales_data.csv', 'r') as file:
    for _ in range(5):
        print(file.readline())

new_sales = pd.read_csv('sales_data.csv')

all_sales = pd.concat([sales.reset_index(), new_sales], ignore_index=True)

print("Shape of all_sales:", all_sales.shape)

all_sales.sort_values(by='Release_Year', inplace=True)

all_sales.reset_index(drop=True, inplace=True)

all_sales.to_csv('all_sales.csv', index=False)

print(all_sales.head())

Index,Product ID,Product Name,Category,Price,Quantity Sold,Brand,Release Year,Ratings

1,153,Microwave,Office Supplies,286.26,12,Philips,2015,3.5

2,114,Smart Light,Wearable,248.16,177,Samsung,2016,3.7

3,286,USB Flash Drive,Audio,1012.2,117,HP,2020,3.9

4,128,External Hard Drive,Wearable,839.11,40,JBL,2017,3.5

Shape of all_sales: (149, 13)


ModuleNotFoundError: No module named 'pandas.io.formats.csvs'

#### About the dataset

Did you notice something odd?
<details>
  <summary>No</summary>
  Take a closer look!
</details>

<details>
  <summary>Yes</summary>
  An Electric Kettle in the category Photography? An Apple Blender in the category Audio? This seems rather odd. We have to admit, we asked ChatGPT to generate 100 additional entries of sample data in 'csv' format. Surprisingly we got a generated csv as response, easy peasy right? Yes but no...

  ChatGPT knew some context (programming in Python) when generating the csv. Let's take a look at the analysis of the reasoning of ChatGPT. What do you see?

  ![GenAI analysis reasoning](analysis.png)

  The dataset is generated using Python code and relies on numpy random. Therefore, there is no correlation between the Product, Product ID, Category, Brand etc. 

  The moral of the story: GenAI results might seem good or qualitative, but take a closer look, be sceptic and check out the reasoning to confirm the quality.


</details>